[[redirects]]
  from = "/Eventos_Page/*"
  to = "/Eventos_Page/eventos.html"
  status = 200

[[redirects]]
  from = "/EventosAbertos_Page/*"
  to = "/EventosAbertos_Page/eventos_abertos.html"
  status = 200

[[redirects]]
  from = "/EventosPassados_Page/*"
  to = "/EventosPassados_Page/eventos_passados.html"
  status = 200

[[redirects]]
  from = "/Gerenciamento de eventos/*"
  to = "/Gerenciamento de eventos/Index.html"
  status = 200

[[redirects]]
  from = "/Home_Page/*"
  to = "/Home_Page/home.html"
  status = 200  

[[redirects]]
  from = "/InfoExpand_Page/*"
  to = "/InfoExpand_Page/infoExp.html"
  status = 200

  [[redirects]]
  from = "/Tela Login e Cadastro/*"
  to = "/Tela Login e Cadastro/login.html"
  status = 200